
package com.landray.kmss.third.ekp.java.notify.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.7
 * 2015-02-27T17:15:47.669+08:00
 * Generated source version: 2.4.7
 */

@WebFault(name = "Exception", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.landray.kmss.third.ekp.java.notify.client.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.landray.kmss.third.ekp.java.notify.client.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.landray.kmss.third.ekp.java.notify.client.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.landray.kmss.third.ekp.java.notify.client.Exception getFaultInfo() {
        return this.exception;
    }
}
