 <%@ page language="java" pageEncoding="UTF-8" contentType="application/x-javascript; charset=UTF-8"%>
<%@ taglib uri="/WEB-INF/kmss.tld" prefix="kmss"%>
<%--Designer_Lang.auditshow_name='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_name" />';
Designer_Lang.auditshow_name_insert='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_name_insert" />';
Designer_Lang.auditshow_auditorOwner='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_auditorOwner" />';
Designer_Lang.auditshow_chooseExhibitionNodes='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_chooseExhibitionNodes" />';
Designer_Lang.auditshow_preference='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_preference" />';
Designer_Lang.auditshow_preferenceHint='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_preferenceHint" />';
Designer_Lang.auditshow_preferenceParam='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_preferenceParam" />';
Designer_Lang.auditshow_auditNode='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_auditNode" />';
Designer_Lang.auditshow_choose='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_choose" />';
Designer_Lang.auditshow_attr_hiddenValue='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_attr_hiddenValue" />';
Designer_Lang.auditshow_attr_hiddenName='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_attr_hiddenName" />';
Designer_Lang.auditshow_attr_type='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_attr_type" />';
Designer_Lang.auditshow_attr_exhibitionStyle='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_attr_exhibitionStyle" />';
Designer_Lang.auditshow_attr_preview='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_attr_preview" />';
Designer_Lang.auditshow_attr_filterNote='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_attr_filterNote" />';
Designer_Lang.auditshow_attr_noteFilter='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_attr_noteFilter" />';
Designer_Lang.auditshow_attr_noteSort='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_attr_noteSort" />';
Designer_Lang.auditshow_mould_handler1='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_mould_handler1" />';
Designer_Lang.auditshow_mould_signature='<kmss:message bundle="sys-lbpmservice-taglib-auditnote" key="Designer_Lang.auditshow_mould_signature" />';
Designer_Lang.auditshow_mould_handler2='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_mould_handler2" />';
Designer_Lang.auditshow_mould_node1='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_mould_node1" />';
Designer_Lang.auditshow_mould_node2='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_mould_node2" />';
Designer_Lang.auditshow_mould_custom='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_mould_custom" />';
Designer_Lang.auditshow_filterNote_sameHandler='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_filterNote_sameHandler" />';
Designer_Lang.auditshow_filterNote_sameDept='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_filterNote_sameDept" />';
Designer_Lang.auditshow_filterNote_assigneeNoteOnly='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_filterNote_assigneeNoteOnly" />';
Designer_Lang.auditshow_filterNote_handlerNoteOnly='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_filterNote_handlerNoteOnly" />';
Designer_Lang.auditshow_sortNote_Asc='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_sortNote_Asc" />';
Designer_Lang.auditshow_sortNote_Desc='<kmss:message bundle="sys-xform-base" key="Designer_Lang.auditshow_sortNote_Desc" />';
 --%>