<%@ page language="java" contentType="text/json; charset=UTF-8"	pageEncoding="UTF-8"%>
[
	{
		"text":"新建会议",
		"href":"http://www.google.com.hk",
		"icon":"lui_icon_l_icon_2"
	},
	{
		"text":"新建日程",
		"href":"http://www.google.com.hk",
		"icon":"lui_icon_l_icon_3"
	},
	{
		"text":"新建规范",
		"href":"http://www.google.com.hk",
		"icon":"lui_icon_l_icon_4"
	},
	{
		"text":"发布新闻",
		"href":"http://www.google.com.hk",
		"icon":"lui_icon_l_icon_5"
	},
	{
		"text":"组织会议",
		"href":"http://www.google.com.hk",
		"icon":"lui_icon_l_icon_6"
	},
	{
		"text":"新建报销",
		"href":"http://www.google.com.hk",
		"icon":"lui_icon_l_icon_7"
	},
	{
		"text":"程序申报",
		"href":"http://www.51js.com",
		"icon":"lui_icon_l_icon_8"
	},
	{
		"text":"流程模版",
		"href":"http://www.google.com.hk",
		"icon":"lui_icon_l_icon_9"
	},
	{
		"text":"流程记录",
		"href":"http://www.google.com.hk",
		"icon":"lui_icon_l_icon_10"
	},
	{
		"text":"新建会议",
		"href":"http://www.google.com.hk",
		"icon":"lui_icon_l_icon_2"
	},
	{
		"text":"新建日程",
		"href":"http://www.google.com.hk",
		"icon":"lui_icon_l_icon_3"
	},
	{
		"text":"新建规范",
		"href":"http://www.google.com.hk",
		"icon":"lui_icon_l_icon_4"
	},
	{
		"text":"发布新闻",
		"href":"http://www.google.com.hk",
		"icon":"lui_icon_l_icon_5"
	},
	{
		"text":"组织会议",
		"href":"http://www.google.com.hk",
		"icon":"lui_icon_l_icon_6"
	}
]