package com.landray.kmss.third.ekp.java.tag.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.2 2017-02-13T18:18:37.768+08:00
 * Generated source version: 2.4.2
 * 
 */
public final class ISysTagWebService_ISysTagWebServicePort_Client {

	private static final QName SERVICE_NAME = new QName(
			"http://webservice.tag.sys.kmss.landray.com/",
			"ISysTagWebServiceService");

	private ISysTagWebService_ISysTagWebServicePort_Client() {
	}

	public static void main(String[] args) throws java.lang.Exception {
		URL wsdlURL = ISysTagWebServiceService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		ISysTagWebServiceService ss = new ISysTagWebServiceService(wsdlURL,
				SERVICE_NAME);
		ISysTagWebService port = ss.getISysTagWebServicePort();

		{
			System.out.println("Invoking getTags...");
			com.landray.kmss.third.ekp.java.tag.client.TagGetTagsContext _getTags_arg0 = new com.landray.kmss.third.ekp.java.tag.client.TagGetTagsContext();
			try {
				com.landray.kmss.third.ekp.java.tag.client.TagGetResult _getTags__return = port
						.getTags(_getTags_arg0);
				System.out.println("getTags.result=" + _getTags__return);

			} catch (Exception_Exception e) {
				System.out
						.println("Expected exception: Exception has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking addTags...");
			com.landray.kmss.third.ekp.java.tag.client.TagAddContext _addTags_arg0 = new com.landray.kmss.third.ekp.java.tag.client.TagAddContext();
			try {
				com.landray.kmss.third.ekp.java.tag.client.TagResult _addTags__return = port
						.addTags(_addTags_arg0);
				System.out.println("addTags.result=" + _addTags__return);

			} catch (Exception_Exception e) {
				System.out
						.println("Expected exception: Exception has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking getCategories...");
			java.lang.String _getCategories_arg0 = "";
			try {
				com.landray.kmss.third.ekp.java.tag.client.TagGetResult _getCategories__return = port
						.getCategories(_getCategories_arg0);
				System.out.println("getCategories.result="
						+ _getCategories__return);

			} catch (Exception_Exception e) {
				System.out
						.println("Expected exception: Exception has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking getGroups...");
			java.lang.String _getGroups_arg0 = "";
			try {
				com.landray.kmss.third.ekp.java.tag.client.TagResult _getGroups__return = port
						.getGroups(_getGroups_arg0);
				System.out.println("getGroups.result=" + _getGroups__return);

			} catch (Exception_Exception e) {
				System.out
						.println("Expected exception: Exception has occurred.");
				System.out.println(e.toString());
			}
		}
		{
	        System.out.println("Invoking getIsSpecialByTags...");
	        java.util.List<java.lang.String> _getIsSpecialByTags_arg0 = null;
	        try {
	        	com.landray.kmss.third.ekp.java.tag.client.TagResult 
	            	_getIsSpecialByTags__return = port.getIsSpecialByTags(_getIsSpecialByTags_arg0);
	            System.out.println("getIsSpecialByTags.result=" + _getIsSpecialByTags__return);

	        } catch (Exception_Exception e) { 
	            System.out.println("Expected exception: Exception has occurred.");
	            System.out.println(e.toString());
	        }
	    }

		System.exit(0);
	}

}
