package com.landray.kmss.third.ekp.java.tag.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2 2017-02-13T18:18:37.976+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://webservice.tag.sys.kmss.landray.com/", name = "ISysTagWebService")
@XmlSeeAlso({ ObjectFactory.class })
public interface ISysTagWebService {

	@WebMethod
	@RequestWrapper(localName = "getTags", targetNamespace = "http://webservice.tag.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.tag.client.GetTags")
	@ResponseWrapper(localName = "getTagsResponse", targetNamespace = "http://webservice.tag.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.tag.client.GetTagsResponse")
	@WebResult(name = "return", targetNamespace = "")
	public com.landray.kmss.third.ekp.java.tag.client.TagGetResult getTags(
			@WebParam(name = "arg0", targetNamespace = "") com.landray.kmss.third.ekp.java.tag.client.TagGetTagsContext arg0)
			throws Exception_Exception;

	@WebMethod
	@RequestWrapper(localName = "addTags", targetNamespace = "http://webservice.tag.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.tag.client.AddTags")
	@ResponseWrapper(localName = "addTagsResponse", targetNamespace = "http://webservice.tag.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.tag.client.AddTagsResponse")
	@WebResult(name = "return", targetNamespace = "")
	public com.landray.kmss.third.ekp.java.tag.client.TagResult addTags(
			@WebParam(name = "arg0", targetNamespace = "") com.landray.kmss.third.ekp.java.tag.client.TagAddContext arg0)
			throws Exception_Exception;

	@WebMethod
	@RequestWrapper(localName = "getCategories", targetNamespace = "http://webservice.tag.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.tag.client.GetCategories")
	@ResponseWrapper(localName = "getCategoriesResponse", targetNamespace = "http://webservice.tag.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.tag.client.GetCategoriesResponse")
	@WebResult(name = "return", targetNamespace = "")
	public com.landray.kmss.third.ekp.java.tag.client.TagGetResult getCategories(
			@WebParam(name = "arg0", targetNamespace = "") java.lang.String arg0)
			throws Exception_Exception;

	@WebMethod
	@RequestWrapper(localName = "getGroups", targetNamespace = "http://webservice.tag.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.tag.client.GetGroups")
	@ResponseWrapper(localName = "getGroupsResponse", targetNamespace = "http://webservice.tag.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.tag.client.GetGroupsResponse")
	@WebResult(name = "return", targetNamespace = "")
	public com.landray.kmss.third.ekp.java.tag.client.TagResult getGroups(
			@WebParam(name = "arg0", targetNamespace = "") java.lang.String arg0)
			throws Exception_Exception;
	
	@WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getIsSpecialByTags", targetNamespace = "http://webservice.tag.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.tag.client.GetIsSpecialByTags")
    @WebMethod
    @ResponseWrapper(localName = "getIsSpecialByTagsResponse", targetNamespace = "http://webservice.tag.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.tag.client.GetIsSpecialByTagsResponse")
    public com.landray.kmss.third.ekp.java.tag.client.TagResult getIsSpecialByTags(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0
    ) throws Exception_Exception;
}
