package com.landray.kmss.third.ekp.java.tag.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2 2017-02-15T10:27:20.443+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "ISysTagWebServiceService", wsdlLocation = "http://localhost:8080/kms/sys/webservice/sysTagWebService?wsdl", targetNamespace = "http://webservice.tag.sys.kmss.landray.com/")
public class ISysTagWebServiceService extends Service {

	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName(
			"http://webservice.tag.sys.kmss.landray.com/",
			"ISysTagWebServiceService");
	public final static QName ISysTagWebServicePort = new QName(
			"http://webservice.tag.sys.kmss.landray.com/",
			"ISysTagWebServicePort");
	static {
		URL url = null;
		try {
			url = new URL(
					"http://localhost:8080/kms/sys/webservice/sysTagWebService?wsdl");
		} catch (MalformedURLException e) {
			org.slf4j.LoggerFactory.getLogger(ISysTagWebServiceService.class.getName()).error(
							"Can not initialize the default wsdl from {0}",
							"http://localhost:8080/kms/sys/webservice/sysTagWebService?wsdl");
		}
		WSDL_LOCATION = url;
	}

	public ISysTagWebServiceService(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public ISysTagWebServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ISysTagWebServiceService() {
		super(WSDL_LOCATION, SERVICE);
	}

	/**
	 *
	 * @return returns ISysTagWebService
	 */
	@WebEndpoint(name = "ISysTagWebServicePort")
	public ISysTagWebService getISysTagWebServicePort() {
		return super.getPort(ISysTagWebServicePort, ISysTagWebService.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns ISysTagWebService
	 */
	@WebEndpoint(name = "ISysTagWebServicePort")
	public ISysTagWebService getISysTagWebServicePort(
			WebServiceFeature... features) {
		return super.getPort(ISysTagWebServicePort, ISysTagWebService.class,
				features);
	}

}
