package com.landray.kmss.third.ekp.java.notify.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.7
 * 2015-02-27T17:15:47.691+08:00
 * Generated source version: 2.4.7
 * 
 */
@WebServiceClient(name = "ISysNotifyTodoWebServiceService", 
                  wsdlLocation = "http://localhost:8080/ekp/sys/webservice/sysNotifyTodoWebService?wsdl",
                  targetNamespace = "http://webservice.notify.sys.kmss.landray.com/") 
public class ISysNotifyTodoWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.notify.sys.kmss.landray.com/", "ISysNotifyTodoWebServiceService");
    public final static QName ISysNotifyTodoWebServicePort = new QName("http://webservice.notify.sys.kmss.landray.com/", "ISysNotifyTodoWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ekp/sys/webservice/sysNotifyTodoWebService?wsdl");
        } catch (MalformedURLException e) {
            org.slf4j.LoggerFactory.getLogger(ISysNotifyTodoWebServiceService.class.getName())
                .info(
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ekp/sys/webservice/sysNotifyTodoWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ISysNotifyTodoWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ISysNotifyTodoWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISysNotifyTodoWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ISysNotifyTodoWebService
     */
    @WebEndpoint(name = "ISysNotifyTodoWebServicePort")
    public ISysNotifyTodoWebService getISysNotifyTodoWebServicePort() {
        return super.getPort(ISysNotifyTodoWebServicePort, ISysNotifyTodoWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISysNotifyTodoWebService
     */
    @WebEndpoint(name = "ISysNotifyTodoWebServicePort")
    public ISysNotifyTodoWebService getISysNotifyTodoWebServicePort(WebServiceFeature... features) {
        return super.getPort(ISysNotifyTodoWebServicePort, ISysNotifyTodoWebService.class, features);
    }

}
