
package com.landray.kmss.third.ekp.java.notify.client.v2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.2
 * 2021-01-08T11:15:33.956+08:00
 * Generated source version: 2.4.2
 */

@WebFault(name = "Exception", targetNamespace = "http://ekpj.webservice.notify.sys.kmss.landray.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.landray.kmss.third.ekp.java.notify.client.v2.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.landray.kmss.third.ekp.java.notify.client.v2.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.landray.kmss.third.ekp.java.notify.client.v2.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.landray.kmss.third.ekp.java.notify.client.v2.Exception getFaultInfo() {
        return this.exception;
    }
}
