
package com.landray.kmss.third.ekp.java.notify.client.v2;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2021-01-08T11:15:33.752+08:00
 * Generated source version: 2.4.2
 * 
 */
public final class ISysNotifyTodoWebServiceEkpj_ISysNotifyTodoWebServiceEkpjPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ekpj.webservice.notify.sys.kmss.landray.com/", "ISysNotifyTodoWebServiceEkpjService");

    private ISysNotifyTodoWebServiceEkpj_ISysNotifyTodoWebServiceEkpjPort_Client() {
    }

    public static void main(String[] args) throws java.lang.Exception {
        URL wsdlURL = ISysNotifyTodoWebServiceEkpjService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ISysNotifyTodoWebServiceEkpjService ss = new ISysNotifyTodoWebServiceEkpjService(wsdlURL, SERVICE_NAME);
        ISysNotifyTodoWebServiceEkpj port = ss.getISysNotifyTodoWebServiceEkpjPort();  
        
        {
        System.out.println("Invoking setPersonsDone...");
        com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoClearContext _setPersonsDone_arg0 = new com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoClearContext();
        try {
            com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoAppResult _setPersonsDone__return = port.setPersonsDone(_setPersonsDone_arg0);
            System.out.println("setPersonsDone.result=" + _setPersonsDone__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking add...");
        com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoSendContext _add_arg0 = new com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoSendContext();
        try {
            com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoAppResult _add__return = port.add(_add_arg0);
            System.out.println("add.result=" + _add__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllTodoId...");
        com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoGetAllContext _getAllTodoId_arg0 = new com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoGetAllContext();
        try {
            com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoAppResult _getAllTodoId__return = port.getAllTodoId(_getAllTodoId_arg0);
            System.out.println("getAllTodoId.result=" + _getAllTodoId__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking removeDonePerson...");
        com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoClearContext _removeDonePerson_arg0 = new com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoClearContext();
        try {
            com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoAppResult _removeDonePerson__return = port.removeDonePerson(_removeDonePerson_arg0);
            System.out.println("removeDonePerson.result=" + _removeDonePerson__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking remove...");
        com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoClearContext _remove_arg0 = new com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoClearContext();
        try {
            com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoAppResult _remove__return = port.remove(_remove_arg0);
            System.out.println("remove.result=" + _remove__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking clearTodoPersons...");
        com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoClearContext _clearTodoPersons_arg0 = new com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoClearContext();
        try {
            com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoAppResult _clearTodoPersons__return = port.clearTodoPersons(_clearTodoPersons_arg0);
            System.out.println("clearTodoPersons.result=" + _clearTodoPersons__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking setTodoDone...");
        com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoClearContext _setTodoDone_arg0 = new com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoClearContext();
        try {
            com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoAppResult _setTodoDone__return = port.setTodoDone(_setTodoDone_arg0);
            System.out.println("setTodoDone.result=" + _setTodoDone__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllTodo...");
        com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoGetAllContext _getAllTodo_arg0 = new com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoGetAllContext();
        try {
            com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoAppResult _getAllTodo__return = port.getAllTodo(_getAllTodo_arg0);
            System.out.println("getAllTodo.result=" + _getAllTodo__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateTodo...");
        com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoUpdateContext _updateTodo_arg0 = new com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoUpdateContext();
        try {
            com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoAppResult _updateTodo__return = port.updateTodo(_updateTodo_arg0);
            System.out.println("updateTodo.result=" + _updateTodo__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
