package com.landray.kmss.third.ekp.java.notify.client.v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2021-01-08T11:15:33.991+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ekpj.webservice.notify.sys.kmss.landray.com/", name = "ISysNotifyTodoWebServiceEkpj")
@XmlSeeAlso({ObjectFactory.class})
public interface ISysNotifyTodoWebServiceEkpj {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setPersonsDone", targetNamespace = "http://ekpj.webservice.notify.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.notify.client.v2.SetPersonsDone")
    @WebMethod
    @ResponseWrapper(localName = "setPersonsDoneResponse", targetNamespace = "http://ekpj.webservice.notify.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.notify.client.v2.SetPersonsDoneResponse")
    public com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoAppResult setPersonsDone(
        @WebParam(name = "arg0", targetNamespace = "")
        com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoClearContext arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ekpj.webservice.notify.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.notify.client.v2.Add")
    @WebMethod
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ekpj.webservice.notify.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.notify.client.v2.AddResponse")
    public com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoAppResult add(
        @WebParam(name = "arg0", targetNamespace = "")
        com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoSendContext arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllTodoId", targetNamespace = "http://ekpj.webservice.notify.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.notify.client.v2.GetAllTodoId")
    @WebMethod
    @ResponseWrapper(localName = "getAllTodoIdResponse", targetNamespace = "http://ekpj.webservice.notify.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.notify.client.v2.GetAllTodoIdResponse")
    public com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoAppResult getAllTodoId(
        @WebParam(name = "arg0", targetNamespace = "")
        com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoGetAllContext arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "removeDonePerson", targetNamespace = "http://ekpj.webservice.notify.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.notify.client.v2.RemoveDonePerson")
    @WebMethod
    @ResponseWrapper(localName = "removeDonePersonResponse", targetNamespace = "http://ekpj.webservice.notify.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.notify.client.v2.RemoveDonePersonResponse")
    public com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoAppResult removeDonePerson(
        @WebParam(name = "arg0", targetNamespace = "")
        com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoClearContext arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "remove", targetNamespace = "http://ekpj.webservice.notify.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.notify.client.v2.Remove")
    @WebMethod
    @ResponseWrapper(localName = "removeResponse", targetNamespace = "http://ekpj.webservice.notify.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.notify.client.v2.RemoveResponse")
    public com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoAppResult remove(
        @WebParam(name = "arg0", targetNamespace = "")
        com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoClearContext arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "clearTodoPersons", targetNamespace = "http://ekpj.webservice.notify.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.notify.client.v2.ClearTodoPersons")
    @WebMethod
    @ResponseWrapper(localName = "clearTodoPersonsResponse", targetNamespace = "http://ekpj.webservice.notify.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.notify.client.v2.ClearTodoPersonsResponse")
    public com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoAppResult clearTodoPersons(
        @WebParam(name = "arg0", targetNamespace = "")
        com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoClearContext arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setTodoDone", targetNamespace = "http://ekpj.webservice.notify.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.notify.client.v2.SetTodoDone")
    @WebMethod
    @ResponseWrapper(localName = "setTodoDoneResponse", targetNamespace = "http://ekpj.webservice.notify.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.notify.client.v2.SetTodoDoneResponse")
    public com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoAppResult setTodoDone(
        @WebParam(name = "arg0", targetNamespace = "")
        com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoClearContext arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllTodo", targetNamespace = "http://ekpj.webservice.notify.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.notify.client.v2.GetAllTodo")
    @WebMethod
    @ResponseWrapper(localName = "getAllTodoResponse", targetNamespace = "http://ekpj.webservice.notify.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.notify.client.v2.GetAllTodoResponse")
    public com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoAppResult getAllTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoGetAllContext arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateTodo", targetNamespace = "http://ekpj.webservice.notify.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.notify.client.v2.UpdateTodo")
    @WebMethod
    @ResponseWrapper(localName = "updateTodoResponse", targetNamespace = "http://ekpj.webservice.notify.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.notify.client.v2.UpdateTodoResponse")
    public com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoAppResult updateTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        com.landray.kmss.third.ekp.java.notify.client.v2.NotifyTodoUpdateContext arg0
    ) throws Exception_Exception;
}
