package com.landray.kmss.third.ekp.java.notify.client.v2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2021-01-08T11:15:34.032+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "ISysNotifyTodoWebServiceEkpjService", 
                  wsdlLocation = "http://localhost:8083/ekp/sys/webservice/sysNotifyTodoWebServiceEkpj?wsdl",
                  targetNamespace = "http://ekpj.webservice.notify.sys.kmss.landray.com/") 
public class ISysNotifyTodoWebServiceEkpjService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ekpj.webservice.notify.sys.kmss.landray.com/", "ISysNotifyTodoWebServiceEkpjService");
    public final static QName ISysNotifyTodoWebServiceEkpjPort = new QName("http://ekpj.webservice.notify.sys.kmss.landray.com/", "ISysNotifyTodoWebServiceEkpjPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8083/ekp/sys/webservice/sysNotifyTodoWebServiceEkpj?wsdl");
        } catch (MalformedURLException e) {
            org.slf4j.LoggerFactory.getLogger(ISysNotifyTodoWebServiceEkpjService.class.getName())
                .info(
                     "Can not initialize the default wsdl from {0}", "http://localhost:8083/ekp/sys/webservice/sysNotifyTodoWebServiceEkpj?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ISysNotifyTodoWebServiceEkpjService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ISysNotifyTodoWebServiceEkpjService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISysNotifyTodoWebServiceEkpjService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ISysNotifyTodoWebServiceEkpjService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ISysNotifyTodoWebServiceEkpjService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ISysNotifyTodoWebServiceEkpjService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ISysNotifyTodoWebServiceEkpj
     */
    @WebEndpoint(name = "ISysNotifyTodoWebServiceEkpjPort")
    public ISysNotifyTodoWebServiceEkpj getISysNotifyTodoWebServiceEkpjPort() {
        return super.getPort(ISysNotifyTodoWebServiceEkpjPort, ISysNotifyTodoWebServiceEkpj.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISysNotifyTodoWebServiceEkpj
     */
    @WebEndpoint(name = "ISysNotifyTodoWebServiceEkpjPort")
    public ISysNotifyTodoWebServiceEkpj getISysNotifyTodoWebServiceEkpjPort(WebServiceFeature... features) {
        return super.getPort(ISysNotifyTodoWebServiceEkpjPort, ISysNotifyTodoWebServiceEkpj.class, features);
    }

}
